### ISSUE TITLE
PHPStan ignores paths

### ISSUE THREAD

**Issue by Meldiron** [zed-extensions/php#6]
I have `phpstan.neon`:

```
parameters:
  level: 8
  paths:
    - src/Appwrite/Transformation
  scanDirectories:
    - vendor/swoole/ide-helper
  excludePaths:
    - tests/resources
```

Notice the phpstan only runs in `src/Appwrite/Transformation` directory, so running it with `composer check` (`./vendor/bin/phpstan analyse -c phpstan.neon`) is successful and sees 0 errrors.

But with PHP extension installed in Zed, it shows errors like those:

![Image](https://github.com/user-attachments/assets/deb565e5-b5f8-4f1d-b010-96cb16e1dd44)

Notice it's showing error in file `app/config/...`, which is not included in paths configured for PHPStan.

Is it possible to silent those errors in Zed? Either to respect paths, or to ignore PHPStan all-together; we got CI/CD jobs that would yell at me, if I forget to run it using CLI
